# Generated by Django 3.2.5 on 2021-08-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'uniqu': 'A user with that email already exists.'}, max_length=254, unique=True),
        ),
    ]
