# Generated by Django 3.2.3 on 2021-06-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_friend_friendship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='chat_room_id',
            new_name='room_id',
        ),
    ]
