# Generated by Django 3.2.5 on 2021-07-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_user_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
