# Generated by Django 3.2.7 on 2021-09-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
