# Generated by Django 3.2.3 on 2021-06-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Select', 'null'), ('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], default='Select', max_length=6, null=True),
        ),
    ]
