# Generated by Django 3.2.3 on 2021-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
